# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"first_function": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://fastai.github.io/nbdev/"

git_url = "https://github.com/fastai/nbdev/tree/master/"

def custom_doc_links(name): return None
